import { Link, useLocation } from 'react-router'

const content: Record<string, { title: string; body: string[] }> = {
  '/about': {
    title: 'About MGTV',
    body: [
      'Mining Gold TV (MGTV) is a premium digital entertainment and media platform dedicated to showcasing the best of Caribbean culture, music, sport, and storytelling.',
      'Founded with a mission to elevate Caribbean voices on the global stage, MGTV brings together exclusive original series, live events, music videos, and in-depth news coverage from across the region.',
      'From the rhythms of Jamaica to the festivals of Trinidad, and from the cricket grounds of Barbados to the athletics tracks of the world, MGTV captures every dimension of Caribbean life with cinematic quality and authentic perspective.',
      'MGTV+ offers our premium subscribers an expanded library of exclusive originals, HD streaming, live event access, and more.',
    ],
  },
  '/contact': {
    title: 'Contact Us',
    body: [
      'We would love to hear from you. Whether you have a question about your account, are interested in partnering with MGTV, or want to learn more about advertising opportunities, our team is here to help.',
      'General enquiries: hello@mgtv.com',
      'Business partnerships: partners@mgtv.com',
      'Press & media: press@mgtv.com',
      'Technical support: support@mgtv.com',
      'Our team typically responds within 1–2 business days.',
    ],
  },
  '/privacy': {
    title: 'Privacy Policy',
    body: [
      'Your privacy is important to us. This policy explains how MGTV collects, uses, and protects your personal information when you use our platform.',
      'We collect information you provide directly (such as account registration details), information generated by your use of the platform (such as viewing history and preferences), and information from third-party services where you have authorised such sharing.',
      'We use your data to personalise your experience, improve our services, communicate with you about your account and new content, and where applicable, serve relevant advertising.',
      'We do not sell your personal data to third parties. You have the right to access, correct, or delete your personal information at any time through your account settings.',
      'This policy was last updated: September 2026.',
    ],
  },
  '/terms': {
    title: 'Terms of Use',
    body: [
      'By accessing or using MGTV, you agree to be bound by these Terms of Use. Please read them carefully.',
      'MGTV grants you a limited, non-exclusive, non-transferable licence to access and use the platform for personal, non-commercial purposes.',
      'You agree not to reproduce, distribute, modify, or create derivative works of any content available on the platform without express written permission from MGTV.',
      'MGTV reserves the right to suspend or terminate accounts that violate these terms or engage in conduct detrimental to other users or the platform.',
      'These terms are governed by the laws of Jamaica and any disputes shall be subject to the exclusive jurisdiction of the Jamaican courts.',
      'Last updated: September 2026.',
    ],
  },
}

export function StaticPage() {
  const { pathname } = useLocation()
  const page = content[pathname]

  if (!page) return null

  return (
    <div className="min-h-screen bg-[#0A0A0A] pt-16">
      <div className="max-w-[760px] mx-auto px-8 md:px-12 py-16">
        <Link to="/" className="flex items-center gap-2 text-[#6B6B6B] hover:text-[#C9A84C] transition-colors mb-10 text-sm">
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
          </svg>
          Home
        </Link>
        <h1 className="text-6xl md:text-7xl text-[#F5F5F5] mb-10 leading-none" style={{ fontFamily: 'Bebas Neue, sans-serif' }}>
          {page.title}
        </h1>
        <div className="space-y-5">
          {page.body.map((paragraph, i) => (
            <p key={i} className="text-[#A3A3A3] text-base leading-relaxed">
              {paragraph}
            </p>
          ))}
        </div>
      </div>
    </div>
  )
}
